kind: pipeline
type: docker
name: default
trigger:
  branch:
    - master

steps:

- name: build
  image: ruby
  commands:
  - bundle install
  - bundle exec jekyll build

- name: deploy
  image: ruby
  commands:
  - eval `ssh-agent -s`
  - echo "$RSYNC_KEY" | ssh-add -
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - rsync -rv -e "ssh -p 22" /drone/src/_site/ $RSYNC_USER@$RSYNC_HOST:/opt/static/volumes/nginx/sites/flower.codes/ --checksum
  environment:
    RSYNC_KEY:
      from_secret: rsync_key
    RSYNC_USER:
      from_secret: rsync_user
    RSYNC_HOST:
      from_secret: rsync_host