kind: pipeline
type: docker
name: default
trigger:
  branch:
    - main

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    depends_on: [clone]
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./.bundle
        - ./.jekyll-cache
        - ./.jekyll-metadata

  - name: build
    image: ruby:2.7
    depends_on: [restore-cache]
    commands:
      - export BUNDLE_PATH="./.bundle"
      - bundle install
      - bundle exec jekyll build --incremental

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    depends_on: [build]
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./.bundle
        - ./.jekyll-cache
        - ./.jekyll-metadata

  - name: optimize
    image: v4tech/imagemagick:latest
    depends_on: [clone]
    commands:
      # compress png images
      - mogrify -verbose -strip -resize 800\> -colorspace Gray -colors 4 -quality 10 /drone/src/assets/posts/*.png

      # compress jpg images
      - mogrify -verbose -sampling-factor 4:2:0 -strip -interlace JPEG -resize 800\> -colorspace Gray -colors 4 -quality 10 /drone/src/assets/posts/*.jpg

  - name: deploy
    image: ruby:2.7
    depends_on: [build, optimize]
    commands:
      - apt update
      - apt install rsync -y
      - eval `ssh-agent -s`
      - echo "$RSYNC_KEY" | ssh-add -
      - mkdir -p ~/.ssh
      - echo "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - rsync -rvc /drone/src/_site/ $RSYNC_USER@$RSYNC_HOST:/var/www/flower.codes/
    environment:
      RSYNC_KEY:
        from_secret: rsync_key
      RSYNC_USER:
        from_secret: rsync_user
      RSYNC_HOST:
        from_secret: rsync_host

volumes:
  - name: cache
    host:
      path: /tmp/cache
