pipeline:
  build:
    image: jekyll/builder
    commands:
      - chown -R jekyll:jekyll /drone
      - jekyll build
  publish:
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: registry.flower.codes/blog
      tags: latest

branches: master
