pipeline:
  build:
    image: jekyll/builder
    commands:
      - chown -R jekyll:jekyll /drone
      - jekyll build
  publish:
    image: plugins/docker
		settings:
			username:
				from_secret: docker_username
			password:
				from_secret: docker_password
			auto_tag: true
			repo: registry.flower.codes/blog
			registry: registry.flower.codes

branches: master
