kind: pipeline
type: docker
name: default
trigger:
  branch:
    - main

steps:
  - name: build
    image: ruby:2.7
    commands:
      - export BUNDLE_PATH="./.bundle"
      - make install
      - make http
      - make gopher

  # TODO optimize

  - name: deploy
    image: ruby:2.7
    depends_on: [build]
    commands:
      - apt update
      - apt install rsync -y
      - eval `ssh-agent -s`
      - echo "$RSYNC_KEY" | ssh-add -
      - mkdir -p ~/.ssh
      - echo "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - rsync -rvc /drone/src/_http/ $RSYNC_USER@$RSYNC_HOST:$RSYNC_HTTP_PATH
      - rsync -rvc /drone/src/_gopher/ $RSYNC_USER@$RSYNC_HOST:$RSYNC_GOPHER_PATH
    environment:
      RSYNC_KEY:
        from_secret: rsync_key
      RSYNC_USER:
        from_secret: rsync_user
      RSYNC_HOST:
        from_secret: rsync_host
      RSYNC_HTTP_PATH:
        from_secret: rsync_http_path
      RSYNC_GOPHER_PATH:
        from_secret: rsync_gopher_path