kind: pipeline
type: docker
name: default
trigger:
  branch:
    - main

steps:

- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
    - ./.bundle

- name: build
  image: ruby:2.7
  commands:
  - export BUNDLE_PATH="./.bundle"
  - bundle install
  - bundle exec jekyll build

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
    - ./.bundle

- name: optimize
  image: ruby:2.7
  commands:
  - apt update
  - apt install imagemagick -y

  # compress png images
  - mogrify -verbose -resize '400' -colorspace Gray -colors 4 -quality 10 /drone/src/_site/assets/posts/*.png

  # compress jpg images
  - mogrify -verbose -resize '400' -colorspace Gray -colors 4 -quality 10 /drone/src/_site/assets/posts/*.jpg

- name: deploy
  image: ruby:2.7
  commands:
  - apt update
  - apt install rsync -y
  - eval `ssh-agent -s`
  - echo "$RSYNC_KEY" | ssh-add -
  - mkdir -p ~/.ssh
  - echo "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - rsync -rvc /drone/src/_site/ $RSYNC_USER@$RSYNC_HOST:/var/www/flower.codes/
  environment:
    RSYNC_KEY:
      from_secret: rsync_key
    RSYNC_USER:
      from_secret: rsync_user
    RSYNC_HOST:
      from_secret: rsync_host

volumes:
  - name: cache
    host:
      path: /tmp/cache