kind: pipeline
type: docker
name: default
trigger:
  branch:
    - master

steps:

- name: build
  image: ruby
  commands:
  - bundle install
  - bundle exec jekyll build

- name: optimize
  image: ruby
  commands:
  - apt update
  - apt install imagemagick -y

  # compress png images
  - mogrify -verbose -colorspace Gray -colors 4 -quality 10 /drone/src/_site/assets/posts/*.png

  # compress jpg images
  - mogrify -verbose -colorspace Gray -colors 4 -quality 10 /drone/src/_site/assets/posts/*.jpg

- name: deploy
  image: ruby
  commands:
  - apt update
  - apt install rsync -y
  - eval `ssh-agent -s`
  - echo "$RSYNC_KEY" | ssh-add -
  - mkdir -p ~/.ssh
  - echo "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - rsync -rvc /drone/src/_site/ $RSYNC_USER@$RSYNC_HOST:/opt/static/volumes/nginx/sites/flower.codes/
  environment:
    RSYNC_KEY:
      from_secret: rsync_key
    RSYNC_USER:
      from_secret: rsync_user
    RSYNC_HOST:
      from_secret: rsync_host