pipeline:
  build:
    image: jekyll/builder
    commands:
      - chown -R jekyll:jekyll /drone
      - jekyll build
  publish:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: registry.flower.codes/blog
    registry: registry.flower.codes
    auto_tag: true

branches: master
