kind: pipeline
type: docker
name: default
trigger:
  branch:
    - main

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    depends_on: [clone]
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./.bundle
        - ./.jekyll-cache
        - ./.jekyll-metadata

  - name: build
    image: ruby:2.7
    depends_on: [restore-cache]
    commands:
      - export BUNDLE_PATH="./.bundle"
      - bundle install
      - bundle exec jekyll build --incremental

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    depends_on: [build]
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./.bundle
        - ./.jekyll-cache
        - ./.jekyll-metadata

  - name: optimize
    image: v4tech/imagemagick:latest
    depends_on: [clone]
    commands:
      # compress png images
      - mogrify -verbose -strip -resize 800\> -colorspace Gray -colors 4 -quality 10 /drone/src/assets/posts/*.png

      # compress jpg images
      - mogrify -verbose -sampling-factor 4:2:0 -strip -interlace JPEG -resize 800\> -colorspace Gray -colors 4 -quality 10 /drone/src/assets/posts/*.jpg

  - name: deploy
    image: alpine:latest
    depends_on: [build, optimize]
    volumes:
      - name: destination
        path: /var/www/flower.codes
    commands:
      - cp -rf /drone/src/_site/* /var/www/flower.codes/*

volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: destination
    host:
      path: /var/www/flower.codes