name: jekyll

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: build and deploy
    steps:
      - uses: actions/checkout@v2
      - name: degrade jpgs
        shell: bash
        run: |
          cd ./http/assets/posts/

          for f in *.jpg; do
           if [ -f "${f%.jpg}-degraded.gif" ]; then
              continue
            fi

            convert "${f}" -verbose -format GIF -interlace GIF -resize 640\> -colorspace gray -colors 4 -ordered-dither 8x8 -set filename:f "%[t]-degraded" "%[filename:f].gif"
          done
      - name: commit changes
        id: commit
        shell: bash
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"

          git add ./http/assets/posts

          if [ -z "$(git status --porcelain)" ]; then
             echo "::set-output name=push::false"
          else
             git commit -m "[bot] degraded newly added images"
             echo "::set-output name=push::true"
          fi
      - name: push commit
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
      # - name: set up ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: 2.7
      #     bundler-cache: true
      # - name: set up node
      #   uses: actions/setup-node@v2-beta
      #   with:
      #     node-version: '14'
      # - name: install dependencies
      #   run: make install
      # - name: build http site
      #   run: make http
      # - name: build gopher hole
      #   run: make gopher
      # - name: deploy site to server
      #   uses: burnett01/rsync-deployments@5.0
      #   with:
      #     switches: -avzr --delete
      #     path: _http/
      #     remote_path: /opt/stack/volumes/caddy/site/flower.codes/
      #     remote_host: ${{ secrets.REMOTE_HOST }}
      #     remote_user: deploy
      #     remote_key: ${{ secrets.SSH_KEY }}
      #     remote_key_pass : ${{ secrets.SSH_KEY_PASSPHRASE }}
      # - name: deploy gopherhole to server
      #   uses: burnett01/rsync-deployments@5.0
      #   with:
      #     switches: -avzr --delete
      #     path: _gopher/
      #     remote_path: /opt/stack/volumes/gophernicus/hole/
      #     remote_host: ${{ secrets.REMOTE_HOST }}
      #     remote_user: deploy
      #     remote_key: ${{ secrets.SSH_KEY }}
      #     remote_key_pass : ${{ secrets.SSH_KEY_PASSPHRASE }}