name: jekyll

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8 * * *"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: build and deploy
    steps:
      - uses: actions/checkout@v2
      - name: degrade images
        run: make degrade
      - name: commit changes
        id: commit
        shell: bash
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"

          git add ./http/assets/posts

          if [ -z "$(git status --porcelain)" ]; then
             echo "::set-output name=push::false"
          else
             git commit -m "[bot] degraded newly added images"
             echo "::set-output name=push::true"
          fi
      - name: push commit
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: set up node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: install dependencies
        run: make install
      - name: build everything
        run: make
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: deploy it all to fly.io
        with:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only
