name: degrade-images

on:
  push:
    branches: [ main ]

jobs:
  degrade-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: degrade pngs
        shell: bash
        run: |
          cd ./assets/posts/

          for f in *.png; do
            if [[ "$f" == *-degraded.png ]]; then
              continue
            elif [ -f "${f%.png}-degraded.png" ]; then
              continue
            fi

            convert "${f}" -verbose -strip -resize 800\> -colorspace Gray -colors 4 -quality 10 -set filename:f "%[t]-degraded" "%[filename:f].png"
          done
      - name: degrade jpgs
        shell: bash
        run: |
          cd ./assets/posts/

          for f in *.jpg; do
            if [[ "$f" == *-degraded.jpg ]]; then
              continue
            elif [ -f "${f%.jpg}-degraded.jpg" ]; then
              continue
            fi

            convert "${f}" -verbose -sampling-factor 4:2:0 -strip -interlace JPEG -resize 800\> -colorspace Gray -colors 4 -quality 10 -set filename:f "%[t]-degraded" "%[filename:f].jpg"
          done
      - name: commit changes
        shell: bash
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"

          git add ./assets/posts

          if [ -z "$(git status --porcelain)" ]; then
             echo "::set-output name=push::false"
          else
             git commit -m "[bot] degraded newly added images"
             echo "::set-output name=push::true"
          fi
      - name: push commit
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}